version: '2'

services:

  db:
    build: db
    environment:
      - MYSQL_PASSWORD=test_password

  api:
    build:
      context: api
      dockerfile: Dockerfile.test
    depends_on:
      - db
    environment:
      - NODE_ENV=test
      - MYSQL_PASSWORD=test_password
