version: '2'

services:

  db:
    build: db
    # ports:
    #   - 127.0.0.1:3306:3306
    restart: always
    volumes:
      - tally-data:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=tally_password
      - MYSQL_ROOT_PASSWORD=tally_root_password

  api:
    build: api
    depends_on:
      - db
    # ports:
    #   - 80:80
    restart: always
    environment:
      - MYSQL_PASSWORD=tally_password

  nginx:
    build: nginx
    depends_on:
      - api
    ports:
      - 80:80
    restart: always

  db-backup:
    build:
      context: db
      dockerfile: Dockerfile.backup
    restart: always
    volumes:
      - tally-backup:/backup
    environment:
      - MYSQL_PASSWORD=tally_password
    depends_on:
      - db

volumes:
  tally-data:
    driver: local
  tally-backup:
    driver: local
