version: '2'

services:

  db-test:
    build: db
    environment:
      - MYSQL_PASSWORD=test_password
      - MYSQL_ROOT_PASSWORD=test_root_password

  api-test:
    build:
      context: api
      dockerfile: Dockerfile.test
    depends_on:
      - db-test
    environment:
      - MYSQL_PASSWORD=test_password
      - MYSQL_HOST=db-test
